apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: heartbeat-ingress
spec:
  rules:
  - host: heartbeat.localdev.net
    http:
      paths:
      - path: /
        backend:
          serviceName: heartbeat
          servicePort: 80
